import type { CuratedProduct } from './types';

/**
 * Editorial Registry for Daily Ideas Store.
 * Curated finds for kitchen, home, storage, style, cleaning, and self-care.
 */
export const STOREFRONT_URL = 'https://link.amazon/B09VM5pTA';

export const CURATED_PRODUCTS: Record<string, CuratedProduct> = {
  // Legacy Verified Curated Products
  'madamelique-turkish-towels': {
    id: 'madamelique-turkish-towels',
    name: 'Exclusive Turkish Hand Towels (Set of 2, 18" x 40")',
    brand: 'Madamelique',
    category: 'home',
    description: 'Decorative 100% pure cotton peshtemal hand towels with woven fringe detailing for bathroom, kitchen, and daily living.',
    editorialNote: 'Lightweight, ultra-absorbent, and fast-drying compared to standard bulky terrycloth towels.',
    affiliateUrl: 'https://link.amazon/B05sw4NKM',
    asin: 'B091ZHTF2F',
    priceRange: '$18–$24',
    badge: 'Pure Cotton Craft Pick',
  },
  'northern-galaxy-aurora-projector': {
    id: 'northern-galaxy-aurora-projector',
    name: 'Northern Galaxy Light Aurora Projector',
    brand: 'HODANS',
    category: 'home',
    description: 'Multifunctional LED nebula star and aurora projector with 33 lighting effects, 8 soothing white noise audio profiles, remote control, and built-in Bluetooth speaker.',
    editorialNote: 'Transforms bedrooms and workspaces into calming, ambient environments for sleep and deep relaxation.',
    affiliateUrl: 'https://link.amazon/B054ctYhZ',
    asin: 'B0B4518KC2',
    priceRange: '$29–$39',
    badge: 'Ambient Lighting Pick',
  },
  'lagraty-chunky-knit-blanket': {
    id: 'lagraty-chunky-knit-blanket',
    name: 'Handmade Chunky Knit Throw Blanket (50" x 60")',
    brand: "L'AGRATY",
    category: 'home',
    description: 'Soft, breathable chenille cable-knit throw blanket crafted for living room sofas, lounge chairs, and bedroom layering.',
    editorialNote: 'Heavyweight cozy texture that provides breathable warmth without shedding or irritating sensitive skin.',
    affiliateUrl: 'https://link.amazon/B09R3RCQW',
    asin: 'B0BR728TB6',
    priceRange: '$35–$49',
    badge: 'Comfort & Texture Pick',
  },
  'lifewit-clothes-storage-bins': {
    id: 'lifewit-clothes-storage-bins',
    name: '100L Large Clothes & Blanket Storage Bins (6 Pack)',
    brand: 'Lifewit',
    category: 'storage',
    description: 'Large-capacity 100-liter foldable fabric organizer bags with clear view front windows, reinforced webbing handles, and durable two-way zippers.',
    editorialNote: 'Essential for seasonal wardrobe transitions, under-bed comforter storage, and spatial decluttering.',
    affiliateUrl: 'https://link.amazon/B00Wor86A',
    asin: 'B0F8NGSQ2J',
    priceRange: '$25–$35',
    badge: 'Spatial Organization Pick',
  },

  // 16 Verified Amazon Products
  'iuv-western-cowgirl-boots': {
    id: 'iuv-western-cowgirl-boots',
    name: 'IUV Embroidered Pointed Toe Western Cowgirl Boots',
    brand: 'IUV',
    category: 'style',
    description: 'Mid-calf pull-on Western boots featuring classic embroidery, pointed toe silhouette, side pull tabs, and a low Cuban heel for daily wear.',
    editorialNote: 'Combines traditional Western stitching with a walkable low heel suitable for casual dresses, denim, and seasonal layering.',
    affiliateUrl: 'https://link.amazon/B07zWpUB4',
    asin: 'B0DTHHK2S1',
    badge: 'Western Style Pick',
  },
  'elegant-comfort-king-fitted-sheet': {
    id: 'elegant-comfort-king-fitted-sheet',
    name: 'Elegant Comfort Deep-Pocket Microfiber King Fitted Sheet',
    brand: 'Elegant Comfort',
    category: 'home',
    description: 'Individual king-size fitted bed sheet crafted from breathable, wrinkle-resistant brushed microfiber with all-around elastic and deep pockets for mattresses up to 16 inches.',
    editorialNote: 'Ideal when you need to replace or rotate a high-wear bottom sheet without purchasing a full multi-piece bedding bundle.',
    affiliateUrl: 'https://link.amazon/B079VepZB',
    asin: 'B07KXN9V67',
    badge: 'Bedding Essential',
  },
  'cyskxyi-swinging-ghost-decoration': {
    id: 'cyskxyi-swinging-ghost-decoration',
    name: 'CYSKXYI 5-Foot Hanging Swinging Ghost Outdoor Décor',
    brand: 'CYSKXYI',
    category: 'home',
    description: 'Five-foot hanging outdoor Halloween decoration featuring a posable flying ghost silhouette with internal LED illumination and flexible suspension lines for porch or tree displays.',
    editorialNote: 'Adds atmospheric holiday movement and illumination to front porches and yards with simple, lightweight hanging installation.',
    affiliateUrl: 'https://link.amazon/B0isaIph6',
    asin: 'B0H1W18KGL',
    badge: 'Seasonal Décor Pick',
  },
  'dr-melaxin-cemenrete-calcium-multi-balm': {
    id: 'dr-melaxin-cemenrete-calcium-multi-balm',
    name: 'Dr.Melaxin Cemenrete Calcium Nourishing Multi Balm Stick',
    brand: 'Dr.Melaxin',
    category: 'self-care',
    description: 'Solid portable hydration balm stick formulated with calcium and moisturizing lipid complexes designed for targeted application on dry facial areas and neck lines.',
    editorialNote: 'A travel-friendly balm applicator that delivers targeted barrier moisture on dry zones without leaving a sticky or heavy residue.',
    affiliateUrl: 'https://link.amazon/B0exefrmH',
    asin: 'B0CNCL35CH',
    badge: 'Targeted Hydration Pick',
  },
  'nintiue-dimmable-arc-floor-lamp': {
    id: 'nintiue-dimmable-arc-floor-lamp',
    name: 'Nintiue 65-Inch Fully Dimmable Modern Arc Floor Lamp',
    brand: 'Nintiue',
    category: 'home',
    description: 'Overarching standing floor lamp with a rotatable fabric drum shade, heavy anti-tip base, rotary stepless dimmer switch, and included warm LED bulb.',
    editorialNote: 'The arched cantilever frame extends overhead lighting directly across sofas, reading nooks, and desks without demanding ceiling wiring.',
    affiliateUrl: 'https://link.amazon/B0amY6llW',
    asin: 'B095NXXP8C',
    badge: 'Living Room Lighting Pick',
  },
  'the-beer-valley-yellow-chindi-rug': {
    id: 'the-beer-valley-yellow-chindi-rug',
    name: 'THE BEER VALLEY Handwoven Yellow Cotton Chindi Area Rug',
    brand: 'THE BEER VALLEY',
    category: 'home',
    description: 'Textured 2x3 foot hand-loomed accent rug made from recycled cotton fabric strips featuring vibrant yellow tones and fringe trim for entryways, kitchens, and hallways.',
    editorialNote: 'Handcrafted chindi weave provides warm visual texture, natural underfoot cushioning, and cheerful color for compact entry and kitchen spaces.',
    affiliateUrl: 'https://link.amazon/B02bkZwVE',
    asin: 'B08GH41N87',
    badge: 'Handwoven Accent Pick',
  },
  'mulwr-travertine-bathroom-tray': {
    id: 'mulwr-travertine-bathroom-tray',
    name: 'MULWR Natural Beige Travertine Stone Vanity Tray',
    brand: 'MULWR',
    category: 'home',
    description: 'Heavyweight rectangular vanity organizer crafted from solid polished natural beige travertine stone with protective silicone foot pads for bathroom counters and dressers.',
    editorialNote: 'Substantial natural stone construction with organic porous texture elevates everyday perfume bottles, soaps, and jewelry organization.',
    affiliateUrl: 'https://link.amazon/B0dycBsOk',
    asin: 'B0D9TCFRJ5',
    badge: 'Natural Stone Vanity Pick',
  },
  'alpine-corporation-tabletop-water-fountain': {
    id: 'alpine-corporation-tabletop-water-fountain',
    name: 'Alpine Corporation Tiered Tabletop Relaxation Water Fountain',
    brand: 'Alpine Corporation',
    category: 'home',
    description: 'Compact indoor tabletop water fountain featuring cascading textured bowls, natural river stones, quiet submersible electric pump, and warm ambient illumination.',
    editorialNote: 'Creates gentle, soothing running water acoustics to mask background noise in home offices, meditation corners, and bedside tables.',
    affiliateUrl: 'https://link.amazon/B04Kl1BNM',
    asin: 'B002YKMPQ6',
    badge: 'Ambient Sound Pick',
  },
  'lifewit-60l-underbed-storage-bags': {
    id: 'lifewit-60l-underbed-storage-bags',
    name: 'Lifewit 60L Foldable Under-Bed Storage Organizer Bags (6-Pack)',
    brand: 'Lifewit',
    category: 'storage',
    description: 'Low-profile 60-liter fabric storage containers featuring reinforced side carry handles, two-way heavy-duty zippers, and a wide transparent PVC top window for seasonal clothing and linens.',
    editorialNote: 'Low-profile design slides easily into shallow spaces under bed frames to organize extra blankets, winter sweaters, and seasonal textiles.',
    affiliateUrl: 'https://link.amazon/B0arzMCtg',
    asin: 'B09ZV2TX28',
    badge: 'Space-Saving Storage Pick',
  },
  'trendy-queen-oversized-fleece-hoodie': {
    id: 'trendy-queen-oversized-fleece-hoodie',
    name: "Trendy Queen Women's Casual Oversized Fleece Pullover Hoodie",
    brand: 'Trendy Queen',
    category: 'style',
    description: 'Relaxed drop-shoulder fleece hoodie with a front kangaroo pocket, ribbed cuffs and hem, and a soft brushed interior for everyday comfort.',
    editorialNote: 'A comfortable, cozy wardrobe staple with a slouchy relaxed drape that pairs effortlessly with leggings, bike shorts, or denim.',
    affiliateUrl: 'https://link.amazon/B0bUpIGar',
    asin: 'B0C65T7727',
    badge: 'Everyday Comfort Pick',
  },
  'truly-soft-everyday-full-sheet-set': {
    id: 'truly-soft-everyday-full-sheet-set',
    name: 'TRULY SOFT Everyday Brushed Microfiber 4-Piece Sheet Set',
    brand: 'TRULY SOFT',
    category: 'home',
    description: 'Four-piece full-size bedding set including one flat sheet, one all-around elastic fitted sheet, and two matching pillowcases crafted from double-brushed microfiber.',
    editorialNote: 'Provides soft, lightweight, fade-resistant bedding that launders easily with minimal wrinkling for everyday bedrooms and guest suites.',
    affiliateUrl: 'https://link.amazon/B08rC9igT',
    asin: 'B01NBJEKX2',
    badge: 'Bedding Value Pick',
  },
  'celimax-pore-dark-spot-brightening-cream': {
    id: 'celimax-pore-dark-spot-brightening-cream',
    name: 'celimax TXA Tranexamic Acid & Niacinamide Brightening Cream',
    brand: 'celimax',
    category: 'self-care',
    description: 'Gentle daily facial cream containing tranexamic acid (TXA), niacinamide, and soothing botanicals to hydrate and support an even-toned skin complexion.',
    editorialNote: 'Combines well-studied cosmetic brighteners in a non-greasy moisturizing cream base designed for post-blemish tone support.',
    affiliateUrl: 'https://link.amazon/B054USqXz',
    asin: 'B0DHKSF81K',
    badge: 'Tone & Clarity Pick',
  },
  'frideko-home-smart-rgb-floor-lamp': {
    id: 'frideko-home-smart-rgb-floor-lamp',
    name: 'FRIDEKO HOME Smart RGB Modern Column Floor Lamp',
    brand: 'FRIDEKO HOME',
    category: 'home',
    description: 'Tall contemporary floor lamp with natural fabric shade, app and remote control, millions of customizable RGB colors, and tunable warm-to-cool white light.',
    editorialNote: 'Offers dual utility as both practical everyday reading illumination and customizable mood lighting for living rooms or bedrooms.',
    affiliateUrl: 'https://link.amazon/B09PbfKuR',
    asin: 'B0D6G5S35J',
    badge: 'Smart Lighting Pick',
  },
  'kozyfly-cotton-braided-area-rug': {
    id: 'kozyfly-cotton-braided-area-rug',
    name: 'KOZYFLY 5x7 Ft Washable Handwoven Cotton Area Rug',
    brand: 'KOZYFLY',
    category: 'home',
    description: 'Reversible flat-weave cotton area rug (5\' x 7\') featuring clean geometric border accents and durable handwoven construction suitable for living rooms and bedrooms.',
    editorialNote: 'Lightweight yet durable natural cotton rug that can be vacuumed or spot cleaned easily, making it great for high-traffic gathering areas.',
    affiliateUrl: 'https://link.amazon/B0eFc8pa5',
    asin: 'B0C235GNV9',
    badge: 'Cotton Living Rug Pick',
  },
  'oliruim-abstract-thinker-statues': {
    id: 'oliruim-abstract-thinker-statues',
    name: 'oliruim Abstract Thinker Resin Statues (Set of 3)',
    brand: 'oliruim',
    category: 'home',
    description: 'Trio of modern minimalist abstract thinker sculptures in distinct contemplating poses, molded from durable resin with a smooth two-tone finish for bookshelves and desks.',
    editorialNote: 'Modern sculptural accent pieces that add visual depth, personality, and intellectual character to open shelving, coffee tables, and desks.',
    affiliateUrl: 'https://link.amazon/B00j5slzz',
    asin: 'B0BJKRYCZF',
    badge: 'Sculptural Accent Pick',
  },
  'wlive-4-drawer-dresser-nightstand': {
    id: 'wlive-4-drawer-dresser-nightstand',
    name: 'WLIVE Compact 4-Drawer Fabric Dresser and Nightstand Tower',
    brand: 'WLIVE',
    category: 'storage',
    description: 'Space-saving vertical organizer tower featuring a sturdy steel frame, wooden water-resistant top surface, and four removable foldable fabric drawers with easy-pull handles.',
    editorialNote: 'Compact footprint fits neatly in narrow closet corners, bedrooms, or entryways to organize clothing accessories, stationery, and small items.',
    affiliateUrl: 'https://link.amazon/B0aLCB05n',
    asin: 'B09SH38JRR',
    badge: 'Compact Storage Pick',
  },
};

/**
 * Helper to fetch contextual picks by product IDs or category
 */
export function getCuratedPicks(idsOrCategory: string[] | string): CuratedProduct[] {
  if (Array.isArray(idsOrCategory)) {
    return idsOrCategory
      .map((id) => CURATED_PRODUCTS[id])
      .filter((p): p is CuratedProduct => Boolean(p));
  }

  return Object.values(CURATED_PRODUCTS).filter((p) => p.category === idsOrCategory);
}
