import type { PillarSlug, OpportunityType, EditorialTopic } from '../editorial/types.ts';
export type { PillarSlug, OpportunityType, EditorialTopic };

/**
 * Supported Social Media Platforms in LifeMode Social Automation V1.
 */
export type SocialPlatform = 'facebook' | 'instagram' | 'pinterest';

export const ALL_SOCIAL_PLATFORMS: SocialPlatform[] = ['facebook', 'instagram', 'pinterest'];

/**
 * Standard visual aspect ratios supported by social automation.
 */
export type SocialImageFormat = '1080x1350' | '1080x1080';

/**
 * Social opportunity representation derived from candidate selection.
 */
export interface SocialOpportunity {
  topicId: string;
  canonicalTopic: string;
  pillar: PillarSlug;
  slug: string;
  totalScore: number;
  socialPotential: number;
  pinterestPotential: number;
  opportunityType: OpportunityType;
  targetPlatforms: SocialPlatform[];
  destinationUrl: string;
  evidence?: Array<{ title: string; url: string; publisher?: string }>;
  tags: string[];
}

/**
 * Structured brief for generating platform-aware social copy and visuals.
 */
export interface SocialBrief {
  briefId: string;
  topicId: string;
  pillar: PillarSlug;
  canonicalTopic: string;
  destinationUrl: string;
  coreConcept: string;
  editorialHook: string;
  targetAudience: string;
  targetPlatforms: SocialPlatform[];
  evidence?: Array<{ title: string; url: string; publisher?: string }>;
  hashtagsHint: string[];
  visualGuidelines: {
    recommendedFormat: SocialImageFormat;
    aestheticStyle: string;
    textOverlayRule: string;
  };
}

/**
 * Structured content generated by the AI for social dissemination.
 */
export interface GeneratedSocialContent {
  topicId: string;
  pillar: PillarSlug;
  concept: string;
  hook: string;
  title: string;
  shortCaption: string;
  extendedCaption?: string;
  callToAction: string;
  hashtags: string[];
  visualConcept: string;
  imageText: {
    headline: string;
    subheadline?: string;
  };
  targetPlatforms: SocialPlatform[];
  sourceReferences?: Array<{ name: string; url: string }>;
  destinationUrl?: string;
}

/**
 * Visual media asset generated for social dissemination.
 */
export interface SocialVisualAsset {
  assetId: string;
  format: SocialImageFormat;
  mimeType: 'image/png' | 'image/jpeg' | 'image/webp' | 'image/svg+xml';
  width: number;
  height: number;
  assetHash: string; // SHA-256 hash of image data
  altText: string;
  headlineOverlay?: string;
  buffer?: Buffer | Uint8Array;
  url?: string;
  isFixture?: boolean;
}

/**
 * Prepared platform-specific package ready for publication.
 */
export interface SocialPlatformPackage {
  platform: SocialPlatform;
  topicId: string;
  contentHash: string;
  caption: string;
  title?: string;
  hashtags: string[];
  destinationUrl?: string;
  boardId?: string; // Pinterest specific
  mediaAsset: SocialVisualAsset;
  preparedPayload: Record<string, any>;
  idempotencyKey: string;
}

/**
 * Result of publishing a platform package.
 */
export interface SocialPlatformPublishResult {
  platform: SocialPlatform;
  status: 'PUBLISHED' | 'DRY_RUN' | 'NOT_CONFIGURED' | 'FAILED' | 'SKIPPED';
  postId?: string;
  postUrl?: string;
  error?: string;
  publishedAt: string;
  idempotencyKey: string;
}

/**
 * AI review result for social content.
 */
export interface SocialReviewResult {
  passed: boolean;
  score: number; // 0-100 (threshold >= 80)
  verdict: 'PASS' | 'REVISE' | 'REJECT';
  feedback: {
    brandAlignment: number; // 0-100
    readability: number; // 0-100
    factuality: number; // 0-100
    safety: number; // 0-100
    platformSuitability: number; // 0-100
    notes: string;
  };
  revisedContent?: GeneratedSocialContent;
}

/**
 * Single manifest / history entry persisted on disk for deduplication & idempotency.
 */
export interface SocialManifestEntry {
  runId: string;
  topicId: string;
  pillar: PillarSlug;
  canonicalTopic: string;
  contentHash: string;
  assetHash: string;
  idempotencyKey: string;
  targetPlatforms: SocialPlatform[];
  platformResults: Partial<Record<SocialPlatform, SocialPlatformPublishResult>>;
  reviewScore: number;
  overallStatus: 'COMPLETED' | 'DRY_RUN' | 'FAILED' | 'REJECTED' | 'PARTIAL';
  createdAt: string;
  updatedAt: string;
}

/**
 * Detailed report for controlled storage-test execution.
 */
export interface StorageTestDetails {
  r2ProviderUsed: 'REAL' | 'FIXTURE';
  objectKey?: string;
  publicUrl?: string;
  facebookPreparation: 'SUCCESS' | 'FAIL';
  instagramPreparation: 'SUCCESS' | 'FAIL';
  pinterestPreparation: 'SUCCESS' | 'FAIL';
  externalPublication: 'SKIPPED';
  gitCommitPush: 'SKIPPED';
}

/**
 * Aggregate summary emitted by the social automation pipeline.
 */
export interface SocialAutomationResult {
  runId: string;
  status: 'SUCCESS' | 'PARTIAL_SUCCESS' | 'SUCCESS_NO_PUBLICATION' | 'FAILED' | 'DRY_RUN';
  startedAt: string;
  completedAt: string;
  durationMs: number;
  dryRun: boolean;
  selectedCount: number;
  processedCount: number;
  succeededCount: number;
  rejectedCount: number;
  failedCount: number;
  publishedCount: number;
  platformSummary: Record<SocialPlatform, { published: number; failed: number; skipped: number }>;
  manifestEntries: SocialManifestEntry[];
  summary: string;
  error?: string;
  storageTestDetails?: StorageTestDetails;
}
