import type { PillarSlug, OpportunityType, EditorialTopic } from '../editorial/types.ts';
export type { PillarSlug, OpportunityType, EditorialTopic };

/**
 * Supported Social Media Platforms in LifeMode Social Automation V1.
 */
/**
 * Supported Social Media Platforms in LifeMode Social Automation.
 */
export type SocialPlatform = 'facebook' | 'instagram' | 'pinterest' | 'threads';

export const ALL_SOCIAL_PLATFORMS: SocialPlatform[] = ['facebook', 'instagram', 'pinterest', 'threads'];

/**
 * Standard visual aspect ratios supported by social automation.
 */
export type SocialImageFormat = '1080x1350' | '1080x1080';

/**
 * Supported social media content types.
 */
export type SocialMediaType = 'image' | 'carousel' | 'video' | 'text';

/**
 * Supported social source projects in the LifeMode ecosystem.
 */
export type SocialSourceProject =
  | 'dreamly-ai'
  | 'ai-zodiac'
  | 'get-ai-set'
  | 'lifemode'
  | 'dreamlyai'
  | 'aizodiac'
  | 'getaiset'
  | string;

/**
 * Social opportunity representation derived from candidate selection.
 */
export interface SocialOpportunity {
  topicId: string;
  canonicalTopic: string;
  pillar: PillarSlug;
  slug: string;
  totalScore: number;
  socialPotential: number;
  pinterestPotential: number;
  opportunityType: OpportunityType;
  targetPlatforms: SocialPlatform[];
  destinationUrl: string;
  evidence?: Array<{ title: string; url: string; publisher?: string }>;
  tags: string[];
  articleTitle?: string;
  articleDescription?: string;
  publishedAt?: string;
  articleImage?: string;
  carouselImages?: string[];
  videoUrl?: string;
  mediaType?: SocialMediaType;
  sourceProject?: string;
}

/**
 * Structured brief for generating platform-aware social copy and visuals.
 */
export interface SocialBrief {
  briefId: string;
  topicId: string;
  pillar: PillarSlug;
  canonicalTopic: string;
  destinationUrl: string;
  coreConcept: string;
  editorialHook: string;
  targetAudience: string;
  targetPlatforms: SocialPlatform[];
  evidence?: Array<{ title: string; url: string; publisher?: string }>;
  hashtagsHint: string[];
  visualGuidelines: {
    recommendedFormat: SocialImageFormat;
    aestheticStyle: string;
    textOverlayRule: string;
  };
  articleTitle?: string;
  articleDescription?: string;
  publishedAt?: string;
  articleImage?: string;
  sourceProject?: string;
}

/**
 * Structured content generated by the AI for social dissemination.
 */
export interface GeneratedSocialContent {
  topicId: string;
  pillar: PillarSlug;
  concept: string;
  hook: string;
  title: string;
  shortCaption: string;
  extendedCaption?: string;
  callToAction: string;
  hashtags: string[];
  visualConcept: string;
  imageText: {
    headline: string;
    subheadline?: string;
  };
  targetPlatforms: SocialPlatform[];
  sourceReferences?: Array<{ name: string; url: string }>;
  destinationUrl?: string;
  sourceProject?: string;
}

/**
 * Visual or multimedia asset generated for social dissemination.
 */
export interface SocialVisualAsset {
  assetId: string;
  format: SocialImageFormat;
  mimeType: 'image/png' | 'image/jpeg' | 'image/webp' | 'image/svg+xml' | 'video/mp4';
  width: number;
  height: number;
  assetHash: string; // SHA-256 hash of media data
  altText: string;
  headlineOverlay?: string;
  buffer?: Buffer | Uint8Array;
  url?: string;
  isFixture?: boolean;
  mediaType?: 'image' | 'video';
  videoUrl?: string;
  durationSeconds?: number;
}

/**
 * Prepared platform-specific package ready for publication.
 */
export interface SocialPlatformPackage {
  platform: SocialPlatform;
  topicId: string;
  contentHash: string;
  caption: string;
  title?: string;
  hashtags: string[];
  destinationUrl?: string;
  boardId?: string; // Pinterest specific
  mediaAsset?: SocialVisualAsset;
  carouselAssets?: SocialVisualAsset[];
  carouselItems?: Array<{
    url: string;
    mediaType?: 'image' | 'video';
    altText?: string;
  }>;
  videoUrl?: string;
  mediaType?: SocialMediaType;
  sourceProject?: string;
  preparedPayload: Record<string, any>;
  idempotencyKey: string;
}

/**
 * Result of publishing a platform package.
 */
export interface SocialPlatformPublishResult {
  platform: SocialPlatform;
  status: 'PUBLISHED' | 'DRY_RUN' | 'NOT_CONFIGURED' | 'FAILED' | 'SKIPPED';
  postId?: string;
  postUrl?: string;
  error?: string;
  publishedAt: string;
  idempotencyKey: string;
}

/**
 * AI review result for social content.
 */
export interface SocialReviewResult {
  passed: boolean;
  score: number; // 0-100 (threshold >= 80)
  verdict: 'PASS' | 'REVISE' | 'REJECT';
  feedback: {
    brandAlignment: number; // 0-100
    readability: number; // 0-100
    factuality: number; // 0-100
    safety: number; // 0-100
    platformSuitability: number; // 0-100
    notes: string;
  };
  revisedContent?: GeneratedSocialContent;
}

/**
 * Single manifest / history entry persisted on disk for deduplication & idempotency.
 */
export interface SocialManifestEntry {
  runId: string;
  topicId: string;
  pillar: PillarSlug;
  canonicalTopic: string;
  contentHash: string;
  assetHash: string;
  idempotencyKey: string;
  sourceProject?: string;
  contentType?: SocialMediaType;
  targetPlatforms: SocialPlatform[];
  platformResults: Partial<Record<SocialPlatform, SocialPlatformPublishResult>>;
  reviewScore: number;
  overallStatus: 'COMPLETED' | 'DRY_RUN' | 'FAILED' | 'REJECTED' | 'PARTIAL';
  createdAt: string;
  updatedAt: string;
}

/**
 * Input package for cross-project content distribution to LifeMode social channels (e.g. Threads).
 */
export interface CrossProjectSocialContent {
  sourceProject: SocialSourceProject;
  contentId: string;
  contentType: 'carousel' | 'video' | 'image' | 'text';
  title: string;
  caption: string;
  destinationUrl?: string;
  hashtags?: string[];
  scheduledDate?: string;
  imageUrl?: string;
  carouselItems?: Array<{
    url: string;
    mediaType?: 'image' | 'video';
    altText?: string;
  }>;
  videoUrl?: string;
  videoDurationSeconds?: number;
  pillar?: PillarSlug;
  targetPlatforms?: SocialPlatform[];
}

/**
 * Result of cross-project social publication.
 */
export interface CrossProjectPublishResult {
  sourceProject: string;
  contentId: string;
  contentType: 'carousel' | 'video' | 'image' | 'text';
  platformResults: Partial<Record<SocialPlatform, SocialPlatformPublishResult>>;
  overallStatus: 'COMPLETED' | 'DRY_RUN' | 'FAILED' | 'SKIPPED' | 'PARTIAL';
  idempotencyKey: string;
  error?: string;
}

/**
 * Detailed report for controlled storage-test execution.
 */
export interface StorageTestDetails {
  r2ProviderUsed: 'REAL' | 'FIXTURE';
  objectKey?: string;
  publicUrl?: string;
  facebookPreparation: 'SUCCESS' | 'FAIL';
  instagramPreparation: 'SUCCESS' | 'FAIL';
  pinterestPreparation: 'SUCCESS' | 'FAIL';
  threadsPreparation?: 'SUCCESS' | 'FAIL';
  externalPublication: 'SKIPPED';
  gitCommitPush: 'SKIPPED';
}

/**
 * Aggregate summary emitted by the social automation pipeline.
 */
export interface SocialAutomationResult {
  runId: string;
  status: 'SUCCESS' | 'PARTIAL_SUCCESS' | 'SUCCESS_NO_PUBLICATION' | 'FAILED' | 'DRY_RUN';
  startedAt: string;
  completedAt: string;
  durationMs: number;
  dryRun: boolean;
  selectedCount: number;
  processedCount: number;
  succeededCount: number;
  rejectedCount: number;
  failedCount: number;
  publishedCount: number;
  platformSummary: Record<SocialPlatform, { published: number; failed: number; skipped: number }>;
  manifestEntries: SocialManifestEntry[];
  summary: string;
  error?: string;
  storageTestDetails?: StorageTestDetails;
}
