import type { RawSourceRecipe } from './types.ts';

/**
 * Curated Seed Recipes from Approved Public Domain Sources.
 * Every recipe is strictly paired 1-to-1 with its original contributor dish photograph.
 */
export const CURATED_SEED_RECIPES: RawSourceRecipe[] = [
  {
    slug: 'fresh-guacamole',
    title: 'Fresh Guacamole',
    description: 'A classic, fresh guacamole made with ripe Hass avocados, lime juice, diced onion, tomato, and fresh cilantro.',
    sourceId: 'based-cooking',
    sourceUrl: 'https://github.com/LukeSmithxyz/based.cooking/blob/master/content/guacamole.md',
    sourceLicense: 'CC0 1.0 Universal',
    sourceAuthor: 'Yaroslav Smirnov',
    prepTime: '10 min',
    cookTime: '0 min',
    totalTime: '10 min',
    servings: '2 portions',
    cuisine: 'Mexican',
    mealType: 'Appetizer / Dip',
    dietaryTags: ['vegan', 'vegetarian', 'gluten-free', 'dairy-free'],
    tags: ['food-drink', 'recipes', 'mexican', 'dips', 'quick-meals'],
    ingredients: [
      '2 ripe Hass avocados',
      '1/4 medium onion, finely minced',
      '1 small Roma tomato, minced',
      'Fresh cilantro, chopped',
      '1 whole fresh lime',
      'Coarse sea salt and freshly ground black pepper to taste',
    ],
    directions: [
      'Cut the avocados in half, remove the pit, and scoop the pulp into a bowl.',
      'Mash the avocados with a fork, add freshly squeezed lime juice, mix and mash until desired texture is reached.',
      'Mince the cilantro, tomato, and onion, then fold them into the avocado mixture.',
      'Season with sea salt and freshly ground black pepper to taste, mixing thoroughly.',
      'Enjoy immediately with warm corn totopos or fresh sliced vegetables.',
    ],
    notes: 'Best consumed fresh, as avocado oxidizes quickly when exposed to air. The lime juice provides acid balance while helping retain vibrant green color.',
    imagePath: '/editorial/food/guacamole.webp',
    imageAlt: 'Fresh homemade guacamole in a rustic bowl with cilantro garnish and totopos',
    imageSource: 'Original photo by Yaroslav Smirnov via Based Cooking (CC0)',
    imageSourceUrl: 'https://github.com/LukeSmithxyz/based.cooking',
    imageLicense: 'CC0 1.0 Universal',
  },
  {
    slug: 'scratch-made-creamy-hummus',
    title: 'Scratch-Made Creamy Hummus',
    description: 'Silky smooth homemade hummus with chickpeas, creamy tahini, fresh lemon juice, crushed garlic, and extra virgin olive oil.',
    sourceId: 'based-cooking',
    sourceUrl: 'https://github.com/LukeSmithxyz/based.cooking/blob/master/content/hummus.md',
    sourceLicense: 'CC0 1.0 Universal',
    sourceAuthor: 'Jacob Smith',
    prepTime: '15 min',
    cookTime: '20 min',
    totalTime: '35 min',
    servings: '6 servings',
    cuisine: 'Middle Eastern',
    mealType: 'Appetizer / Mezze',
    dietaryTags: ['vegan', 'vegetarian', 'gluten-free', 'dairy-free'],
    tags: ['food-drink', 'recipes', 'middle-eastern', 'dips', 'plant-based'],
    ingredients: [
      '1 can (15 oz) cooked chickpeas (or 200g dry soaked chickpeas)',
      '1/2 teaspoon baking soda (if cooking chickpeas from scratch)',
      '1/2 cup quality tahini paste',
      '1/4 cup fresh lemon juice (approx. 1.5 to 2 lemons)',
      '1 to 2 cloves fresh garlic, roughly chopped',
      '1/4 teaspoon ground cumin',
      '1/4 teaspoon za\'atar (optional)',
      '1 tablespoon extra virgin olive oil, plus more for serving',
      '2 to 3 tablespoons ice-cold water',
      'Fine sea salt to taste',
      'Fresh flat-leaf parsley and ground sumac for garnish',
    ],
    directions: [
      'If using canned chickpeas, simmer them for 15–20 minutes with a pinch of baking soda until very soft, then drain and rinse with cold water.',
      'Combine the chopped garlic and fresh lemon juice with a pinch of salt in a food processor. Pulse finely and let rest 10 minutes to mellow raw garlic sharpness.',
      'Add tahini paste to the food processor and blend until thick and creamy.',
      'With the food processor running on high, slowly drizzle in 2 to 3 tablespoons of ice-cold water. Blend until the tahini mixture becomes exceptionally pale, fluffy, and smooth.',
      'Add the warm drained chickpeas and ground cumin. Process on high for 2 to 3 minutes, drizzling in 1 tablespoon of olive oil.',
      'Taste and adjust salt and lemon juice as needed. For extra lightness, add another splash of ice water while blending.',
      'Transfer to a shallow bowl, create a swirl with the back of a spoon, drizzle with extra virgin olive oil, and dust with sumac or za\'atar.',
    ],
    notes: 'The secret to ultra-smooth hummus is whipping tahini and lemon juice with ice-cold water before blending in the cooked chickpeas.',
    imagePath: '/editorial/food/hummus.webp',
    imageAlt: 'Silky creamy hummus plated with olive oil swirl, za\'atar seasoning, and pita bread',
    imageSource: 'Original photo by Jacob Smith via Based Cooking (CC0)',
    imageSourceUrl: 'https://github.com/LukeSmithxyz/based.cooking',
    imageLicense: 'CC0 1.0 Universal',
  },
  {
    slug: 'rustic-potato-leek-soup',
    title: 'Rustic Potato Leek Soup',
    description: 'A comforting, velvety French-style soup made with sweet stewed leeks, tender waxy potatoes, and a touch of heavy cream.',
    sourceId: 'based-cooking',
    sourceUrl: 'https://github.com/LukeSmithxyz/based.cooking/blob/master/content/potato-leek-soup.md',
    sourceLicense: 'CC0 1.0 Universal',
    sourceAuthor: 'cactar',
    prepTime: '15 min',
    cookTime: '80 min',
    totalTime: '95 min',
    servings: '2 portions',
    cuisine: 'French',
    mealType: 'Soup / Main',
    dietaryTags: ['vegetarian', 'gluten-free'],
    tags: ['food-drink', 'recipes', 'soup', 'french', 'comfort-food', 'seasonal-food'],
    ingredients: [
      '3 tablespoons unsalted butter',
      '2 large fresh leeks (white and pale green parts only)',
      '1 quart (4 cups) vegetable or chicken stock',
      '11 ounces waxy potatoes (such as Yukon Gold), peeled and sliced',
      '1 whole bay leaf',
      '3/4 cup heavy cream',
      'Freshly ground white pepper to taste',
      'Fine sea salt to taste',
      '1/2 teaspoon ground nutmeg (optional)',
      '1/2 tablespoon fresh dill weed for garnish (optional)',
    ],
    directions: [
      'Slice the white and light-green parts of the leeks into half-moons, washing thoroughly in cold water to remove any garden grit. Discard dark green tops or save for broth.',
      'Melt butter in a heavy-bottomed soup pot over medium-low heat. Add the leeks and sliced potatoes, cooking slowly for 10 minutes until leeks are soft and translucent without browning.',
      'Pour in the stock, add the bay leaf, ground nutmeg, and white pepper. Bring to a simmer over medium heat, then cover and cook gently for 45–50 minutes until potatoes are fork-tender.',
      'Remove pot from heat and discard the bay leaf.',
      'Use an immersion blender to purée the soup directly in the pot until velvety and smooth.',
      'Gently stir in the heavy cream and season with sea salt to taste. Warm over low heat for 2 minutes without boiling.',
      'Ladle into warm bowls and garnish with fresh dill or cracked white pepper.',
    ],
    notes: 'Sweating the leeks slowly in butter without browning preserves the delicate, sweet vegetable flavor and clean pale color.',
    imagePath: '/editorial/food/potato-leek-soup.webp',
    imageAlt: 'Velvety potato leek soup served in a ceramic bowl with cracked pepper and herb garnish',
    imageSource: 'Original photo by cactar via Based Cooking (CC0)',
    imageSourceUrl: 'https://github.com/LukeSmithxyz/based.cooking',
    imageLicense: 'CC0 1.0 Universal',
  },
  {
    slug: 'artisan-seeded-sourdough-bread',
    title: 'Artisan Seeded Sourdough Bread',
    description: 'A deeply aromatic sourdough loaf packed with pre-soaked whole rye grains, toasted sesame, sunflower seeds, and golden flax.',
    sourceId: 'based-cooking',
    sourceUrl: 'https://github.com/LukeSmithxyz/based.cooking/blob/master/content/sourdough-bread-with-seeds-and-grains.md',
    sourceLicense: 'CC0 1.0 Universal',
    sourceAuthor: 'SirStark',
    prepTime: '15 min (plus overnight soak & fermentation)',
    cookTime: '80 min',
    totalTime: '16 hours (overnight)',
    servings: '1 large loaf (10–12 slices)',
    cuisine: 'European Artisan Baking',
    mealType: 'Bread / Baking',
    dietaryTags: ['vegan', 'vegetarian', 'dairy-free'],
    tags: ['food-drink', 'recipes', 'baking', 'sourdough', 'fermentation', 'grains'],
    ingredients: [
      '400g active mature sourdough starter',
      '300g unbleached wheat bread flour',
      '200g whole rye flour',
      '200g warm water (25–35°C)',
      '20g fine sea salt',
      '2 teaspoons bread spices (coriander, caraway, fennel seeds)',
      '100g whole grain berries (rye, spelt, or wheat berries)',
      '40g flaxseed / linseed',
      '30g raw sesame seeds',
      '30g raw sunflower seeds',
    ],
    directions: [
      'The day before: Simmer the 100g grain berries in 500g water for 45 minutes until tender. In a separate bowl, soak flaxseed, sesame, and sunflower seeds in 100g water. Cover and let both sit overnight (12–16 hours).',
      'Next day: Drain any unabsorbed water from the seeds and cooked grain berries.',
      'In a large mixing bowl, combine the mature sourdough starter, warm water, wheat flour, rye flour, sea salt, bread spices, and the soaked seed mixture.',
      'Knead thoroughly for 8–10 minutes until a cohesive, extensible dough forms.',
      'Shape into a round boule or batard and place in a floured proofing basket. Cover and let ferment in a warm spot (25–30°C) for 4 to 5 hours until noticeably aerated.',
      'Preheat Dutch oven inside oven to 250°C (480°F).',
      'Turn the dough onto parchment, score the top with a sharp baker\'s lame, and transfer into the hot Dutch oven. Cover and bake with trapped steam for 20 minutes.',
      'Remove the lid, lower the oven temperature to 150°C (300°F), and bake for another 50–60 minutes until crust is dark mahogany and sounds hollow when tapped on the base.',
      'Allow the loaf to cool completely on a wire rack for at least 2 hours before slicing.',
    ],
    notes: 'Soaking whole seeds and grain berries overnight ensures they stay moist during baking and prevents them from drawing hydration away from the bread crumb.',
    imagePath: '/editorial/food/sourdough-bread.webp',
    imageAlt: 'Crusty artisan seeded sourdough bread loaf with open crumb on a wooden cutting board',
    imageSource: 'Original photo by SirStark via Based Cooking (CC0)',
    imageSourceUrl: 'https://github.com/LukeSmithxyz/based.cooking',
    imageLicense: 'CC0 1.0 Universal',
  },
  {
    slug: 'baked-pasta-with-broccoli-and-scamorza',
    title: 'Baked Pasta with Broccoli and Scamorza',
    description: 'An Italian baked pasta al forno layered with tender broccoli florets, creamy béchamel sauce, and melted smoked scamorza cheese.',
    sourceId: 'public-domain-recipes',
    sourceUrl: 'https://github.com/ronaldl29/public-domain-recipes/blob/main/content/baked-pasta-with-broccoli.md',
    sourceLicense: 'The Unlicense / Public Domain',
    sourceAuthor: 'Davide Costa',
    prepTime: '15 min',
    cookTime: '30 min',
    totalTime: '45 min',
    servings: '4 servings',
    cuisine: 'Italian',
    mealType: 'Pasta / Main',
    dietaryTags: ['vegetarian'],
    tags: ['food-drink', 'recipes', 'italian', 'pasta', 'cheese', 'seasonal-food'],
    ingredients: [
      '500g short pasta (such as rigatoni, paccheri, or penne)',
      '500g fresh broccoli florets',
      '4 large farm eggs, hard-boiled and sliced',
      '200g smoked scamorza (or provolone) cheese, diced',
      '400g classic silky béchamel sauce',
      '1/3 cup freshly grated Parmigiano-Reggiano',
      'Fresh sage leaves (optional)',
      'Coarse sea salt and freshly ground black pepper to taste',
    ],
    directions: [
      'Bring a large pot of salted water to a rolling boil. Add pasta and cook until very al dente (about 3 minutes less than package directions). Drain and toss with a drop of olive oil.',
      'In a separate pot, blanch broccoli florets in boiling salted water for 6–8 minutes until tender-crisp. Drain well.',
      'Preheat oven to 180°C (350°F). Lightly butter a 9x13-inch baking casserole dish.',
      'Spread a thin foundational layer of béchamel sauce across the bottom of the dish.',
      'Add half the pasta, followed by half the broccoli florets, sliced hard-boiled eggs, and diced scamorza cheese.',
      'Pour over half the remaining béchamel and season with salt and pepper.',
      'Repeat with the remaining pasta, broccoli, eggs, scamorza, and top with the rest of the béchamel sauce.',
      'Scatter grated Parmigiano-Reggiano and fresh sage leaves across the top.',
      'Bake at 180°C for 15–20 minutes until bubbling, then switch to the broiler for 5 minutes until the top is golden and caramelized.',
    ],
    notes: 'Smoked scamorza imparts an earthy, distinctive note that elevates the sweetness of tender broccoli and velvety béchamel.',
    imagePath: '/editorial/food/baked-pasta.webp',
    imageAlt: 'Golden bubbling Italian baked pasta casserole with broccoli florets and melted scamorza cheese',
    imageSource: 'Original photo by Davide Costa via Public Domain Recipes (Unlicense)',
    imageSourceUrl: 'https://github.com/ronaldl29/public-domain-recipes',
    imageLicense: 'The Unlicense / Public Domain',
  },
  {
    slug: 'traditional-flaky-crust-apple-pie',
    title: 'Traditional Flaky Crust Apple Pie',
    description: 'A timeless, double-crust apple pie filled with spiced Golden Delicious apples, cinnamon, nutmeg, and a buttery, flaky homemade pastry.',
    sourceId: 'public-domain-recipes',
    sourceUrl: 'https://github.com/ronaldl29/public-domain-recipes/blob/main/content/apple-pie.md',
    sourceLicense: 'The Unlicense / Public Domain',
    sourceAuthor: 'mfed3',
    prepTime: '30 min',
    cookTime: '45 min',
    totalTime: '75 min',
    servings: '8 servings',
    cuisine: 'American Heritage / Pastry',
    mealType: 'Dessert / Baking',
    dietaryTags: ['vegetarian'],
    tags: ['food-drink', 'recipes', 'baking', 'dessert', 'autumn', 'heritage'],
    ingredients: [
      '900g (approx. 4–5 large) Golden Delicious apples, peeled, cored, and sliced',
      '1 tablespoon fresh lemon juice',
      '50g granulated white sugar',
      '65g light brown sugar',
      '1 teaspoon ground cinnamon',
      '1/4 teaspoon freshly grated nutmeg',
      '1 tablespoon cornstarch',
      '350g all-purpose flour',
      '5g fine sea salt',
      '30g sugar (for dough)',
      '225g (2 sticks) unsalted butter, ice-cold and cubed',
      '50–100ml ice water',
      '1 egg beaten with 1 tablespoon water (for egg wash)',
    ],
    directions: [
      'In a large bowl, toss apple slices with lemon juice, white sugar, brown sugar, cinnamon, nutmeg, and cornstarch. Let sit for 15 minutes to macerate and release natural juices.',
      'Transfer apple mixture to a skillet over medium-low heat and cook for 10–15 minutes until apples soften slightly and juices reduce to a syrup. Remove from heat and let cool.',
      'For the crust: Combine flour, salt, and sugar in a food processor. Add cold cubed butter and pulse until texture resembles coarse cornmeal.',
      'Drizzle in ice water 1 tablespoon at a time, pulsing until dough comes together when pinched.',
      'Divide dough into two disks, wrap in plastic, and chill in refrigerator for 30 minutes.',
      'Preheat oven to 350°F (175°C). Roll out one dough disk on a floured surface to fit a 9-inch pie dish. Press gently into the pan.',
      'Fill with the cooled spiced apple mixture. Roll out second disk and place over apples.',
      'Trim excess overhang, crimp the edges with a fork or fluted fingers, and cut 4 decorative steam vents in the top crust.',
      'Brush top with egg wash for a glossy golden sheen.',
      'Bake at 350°F for 45 minutes until the pastry is deep golden brown and juices bubble through the vents. Cool for 1 hour before slicing.',
    ],
    notes: 'Pre-cooking the apples slightly before baking prevents the common "pie gap" where the fruit shrinks down under the baked top crust.',
    imagePath: '/editorial/food/apple-pie.webp',
    imageAlt: 'Golden brown homemade apple pie with flaky crimped crust and steam vents on a cooling rack',
    imageSource: 'Original photo by mfed3 via Public Domain Recipes (Unlicense)',
    imageSourceUrl: 'https://github.com/ronaldl29/public-domain-recipes',
    imageLicense: 'The Unlicense / Public Domain',
  },
];
