import fs from 'node:fs';
import path from 'node:path';

const manifest = JSON.parse(fs.readFileSync('data/article-rewrite-migration.json', 'utf-8'));
const PROTECTED_SIX = [
  'creative-partnership-oceans-calling-2026',
  'inside-astros-story-spotlight-cultural-impact',
  'cricinfo-reveals-how-cricket-fans-shape-pop-culture',
  'the-enduring-appeal-of-friendlies',
  'why-the-ecuador-south-korea-matchup-keeps-fans-and-critics-talking',
  'guardians-magic-number-how-clevelands-playoff-chase-unfolded',
];

const FORBIDDEN_FIXTURE_PHRASES = [
  'has drawn attention across the modern cultural landscape',
  'This development underscores ongoing structural and tactical shifts within the domain',
  'within a broader lifestyle and industry framework provides essential clarity',
  'observers should monitor verified milestones and official communications',
  'Staying grounded in documented evidence ensures an accurate perspective while filtering out unsubstantiated speculation',
  'Key confirmed benchmarks include: Dates: 2026-10-01',
];

function isFixture(raw: string): boolean {
  for (const phrase of FORBIDDEN_FIXTURE_PHRASES) {
    if (raw.includes(phrase)) return true;
  }
  if (/\w+\*\*\s+\(Reported by/i.test(raw)) return true;
  return false;
}

const articles = Object.values(manifest.articles) as any[];
console.log('Total articles in manifest:', articles.length);

const protectedArticles: any[] = [];
const nonProtectedArticles: any[] = [];

for (const a of articles) {
  const slug = a.slug;
  if (PROTECTED_SIX.includes(slug) || a.isProtectedSix) {
    protectedArticles.push(a);
  } else {
    nonProtectedArticles.push(a);
  }
}

console.log('Protected articles count:', protectedArticles.length);
console.log('Non-protected in manifest count:', nonProtectedArticles.length);

const regeneratedByGroq: any[] = [];
const fixtureRemaining: any[] = [];
const otherArticles: any[] = [];

for (const a of nonProtectedArticles) {
  const fullPath = path.resolve(process.cwd(), a.filePath);
  const raw = fs.readFileSync(fullPath, 'utf-8');
  const fixture = isFixture(raw);
  
  const notesStr = (a.notes || []).join(' ');
  const regenerated = notesStr.includes('Groq LLM') || notesStr.includes('Genuinely rewritten');

  if (fixture) {
    fixtureRemaining.push(a);
  } else if (regenerated) {
    regeneratedByGroq.push(a);
  } else {
    otherArticles.push(a);
  }
}

console.log(`\n=== BREAKDOWN ===`);
console.log(`Regenerated by Groq (Real LLM): ${regeneratedByGroq.length}`);
console.log(`Remaining Fixture Targets: ${fixtureRemaining.length}`);
console.log(`Other (Previously Acceptable Non-Protected / Unchanged): ${otherArticles.length}`);
console.log(`Sum of non-protected: ${regeneratedByGroq.length + fixtureRemaining.length + otherArticles.length}`);
console.log(`Protected: ${protectedArticles.length}`);
console.log(`Total: ${protectedArticles.length + regeneratedByGroq.length + fixtureRemaining.length + otherArticles.length}`);

console.log(`\n=== OTHER ARTICLES (${otherArticles.length}) ===`);
for (const o of otherArticles) {
  console.log(`- [${o.pillar}] ${o.slug} (finalStatus: ${o.finalStatus}, bodyChanged: ${o.bodyChanged}, notes: ${JSON.stringify(o.notes)})`);
}
