import type { OwnedProject, OwnedProjectId } from './types.ts';

export const OWNED_PROJECTS: OwnedProject[] = [
  {
    id: 'ai-zodiac',
    name: 'AI Zodiac',
    tagline: 'Archetypal Patterns & Personality Insights',
    description:
      'Nuanced personality mapping, relational dynamics, and cosmic archetypes explored through intelligent conversational frameworks.',
    url: 'https://play.google.com/store/apps/details?id=com.oberon.aizodiac',
    relevantPillars: ['discover', 'wellbeing', 'life'],
    categories: ['Self-Discovery', 'Archetypes', 'Astrology', 'Personality'],
    ctaLabel: 'Discover AI Zodiac',
    ctaHeadline: 'Explore Personality Archetypes & Self-Discovery',
    ctaDescription:
      'Connect cosmic patterns and personality frameworks with intelligent conversational archetypes.',
    keywords: [
      'astrology',
      'zodiac',
      'horoscope',
      'birth chart',
      'sun sign',
      'moon sign',
      'rising sign',
      'personality archetype',
      'personality type',
      'personality insights',
      'personality framework',
      'self-discovery',
      'enneagram',
      'mbti',
      'archetypal',
      'archetypes',
      'synastry',
      'zodiac compatibility',
      'relationship astrology',
      'cosmic patterns',
      'celestial',
    ],
    negativeKeywords: [
      'sports',
      'betting',
      'match odds',
      'odds',
      'premier league',
      'cricket match',
      'nfl',
      'sleep apnea',
      'insomnia protocol',
    ],
    matchThreshold: 35,
  },
  {
    id: 'dreamly-ai',
    name: 'Dreamly AI',
    tagline: 'Dream Reflection & Sleep Mindfulness',
    description:
      'AI-guided dream journaling, nocturnal pattern analysis, and mindful morning reflections designed for intentional wellbeing.',
    url: 'https://play.google.com/store/apps/details?id=com.oberon.dreamlyai',
    relevantPillars: ['wellbeing', 'life'],
    categories: ['Sleep', 'Dreams', 'Mindfulness', 'Wellbeing'],
    ctaLabel: 'Explore Dreamly AI',
    ctaHeadline: 'Reflect on Your Sleep & Dreams',
    ctaDescription:
      'Capture morning reflections, uncover nocturnal themes, and cultivate a mindful relationship with rest.',
    keywords: [
      'sleep',
      'dreams',
      'dreaming',
      'dream journal',
      'dream interpretation',
      'lucid dreaming',
      'nightmare',
      'nightmares',
      'bedtime',
      'bedtime routine',
      'sleep routine',
      'sleep hygiene',
      'sleep tracking',
      'sleep quality',
      'nocturnal',
      'circadian rhythm',
      'deep sleep',
      'rem sleep',
      'sleep mindfulness',
      'sleep reflection',
      'relaxation before bed',
      'evening wind down',
    ],
    negativeKeywords: [
      'sports',
      'cricket',
      'football',
      'crypto',
      'hardware',
      'coding',
      'betting',
      'odds',
      'investing',
      'personal finance',
    ],
    matchThreshold: 35,
  },
  {
    id: 'get-ai-set',
    name: 'GetAISet',
    tagline: 'Curated AI Toolkits & Workflow Suites',
    description:
      'GetAISet is a multilingual AI education and discovery platform helping learners, professionals, creators, marketers, and developers discover and understand useful AI courses, learning paths, tutorials, tools, comparisons, and practical AI resources.',
    url: 'https://www.getaiset.com/',
    relevantPillars: ['tech-ai', 'money', 'life'],
    categories: ['AI Education', 'AI Tools', 'Learning Paths', 'Productivity'],
    ctaLabel: 'Visit GetAISet',
    ctaHeadline: 'Master AI Tools & Practical Workflows',
    ctaDescription:
      'Discover curated AI courses, tool comparisons, tutorials, and practical workflow suites.',
    keywords: [
      'ai learning',
      'learning ai',
      'learn ai',
      'ai education',
      'ai courses',
      'ai course',
      'ai tutorial',
      'ai tutorials',
      'ai tools',
      'ai tool',
      'ai toolkit',
      'ai toolkits',
      'ai workflow',
      'ai workflows',
      'ai productivity',
      'ai upskilling',
      'prompt engineering course',
      'ai mastery',
      'ai skill development',
      'ai comparison',
      'ai software suite',
      'practical ai resources',
      'learning path',
    ],
    negativeKeywords: [
      'astrology',
      'horoscope',
      'zodiac',
      'sports betting',
      'match odds',
      'dream journaling',
    ],
    matchThreshold: 35,
  },
  {
    id: 'match-signal',
    name: 'MatchSignal',
    tagline: 'Sports Analytics & Strategic Data Insights',
    description:
      'Quantitative match signals, predictive momentum analytics, and data-driven sports intelligence for tactical enthusiasts.',
    url: 'https://matchsignal.pro',
    relevantPillars: ['now', 'discover', 'tech-ai'],
    categories: ['Sports Analytics', 'Match Signals', 'Predictions', 'Data Intelligence'],
    ctaLabel: 'Explore MatchSignal',
    ctaHeadline: 'Data-Driven Sports Signals & Match Analytics',
    ctaDescription:
      'Explore tactical breakdowns, momentum indicators, and quantitative match analytics.',
    keywords: [
      'sports',
      'sports analysis',
      'match analysis',
      'match predictions',
      'game predictions',
      'sports predictions',
      'betting analysis',
      'sports betting',
      'odds',
      'match odds',
      'match preview',
      'fixtures',
      'tactical analysis',
      'sports signals',
      'game stats',
      'sports data',
      'soccer stats',
      'football analytics',
      'cricket match',
      'premier league analysis',
      'champions league',
      'nba predictions',
    ],
    negativeKeywords: [
      'sleep',
      'dreams',
      'astrology',
      'horoscope',
      'skincare',
      'interior design',
      'bedroom design',
    ],
    matchThreshold: 35,
  },
];

export const OWNED_PROJECT_MAP: Record<OwnedProjectId, OwnedProject> = {
  'ai-zodiac': OWNED_PROJECTS[0],
  'dreamly-ai': OWNED_PROJECTS[1],
  'get-ai-set': OWNED_PROJECTS[2],
  'match-signal': OWNED_PROJECTS[3],
};

export function getOwnedProjectById(id: string): OwnedProject | null {
  return (OWNED_PROJECT_MAP as any)[id] || null;
}
